//! Vulkan names for the finite v13 texture-format vocabulary.
//!
//! Capability probing and resource creation share this table. Keeping one
//! mapping authority is correctness-critical: a probe performed with one
//! `VkFormat` and an image created with another would publish a capability the
//! backend did not actually test.

use ash::vk;

use crate::api::format::TextureFormat;

/// Every portable format the current dedicated image creator can name.
pub(super) const FORMATS: &[TextureFormat] = &[
    TextureFormat::R8Unorm,
    TextureFormat::R8Snorm,
    TextureFormat::R8Uint,
    TextureFormat::R8Sint,
    TextureFormat::Rg8Unorm,
    TextureFormat::Rg8Snorm,
    TextureFormat::Rg8Uint,
    TextureFormat::Rg8Sint,
    TextureFormat::Rgba8Unorm,
    TextureFormat::Rgba8UnormSrgb,
    TextureFormat::Rgba8Snorm,
    TextureFormat::Rgba8Uint,
    TextureFormat::Rgba8Sint,
    TextureFormat::Bc1RgbaUnorm,
    TextureFormat::Bc1RgbaUnormSrgb,
    TextureFormat::Bc2RgbaUnorm,
    TextureFormat::Bc2RgbaUnormSrgb,
    TextureFormat::Bc3RgbaUnorm,
    TextureFormat::Bc3RgbaUnormSrgb,
    TextureFormat::Bc4RUnorm,
    TextureFormat::Bc4RSnorm,
    TextureFormat::Bc5RgUnorm,
    TextureFormat::Bc5RgSnorm,
    TextureFormat::Bc6hRgbUfloat,
    TextureFormat::Bc6hRgbFloat,
    TextureFormat::Bc7RgbaUnorm,
    TextureFormat::Bc7RgbaUnormSrgb,
    TextureFormat::Etc2Rgb8Unorm,
    TextureFormat::Etc2Rgb8UnormSrgb,
    TextureFormat::Etc2Rgb8A1Unorm,
    TextureFormat::Etc2Rgb8A1UnormSrgb,
    TextureFormat::Etc2Rgba8Unorm,
    TextureFormat::Etc2Rgba8UnormSrgb,
    TextureFormat::EacR11Unorm,
    TextureFormat::EacR11Snorm,
    TextureFormat::EacRg11Unorm,
    TextureFormat::EacRg11Snorm,
    TextureFormat::Astc4x4Unorm,
    TextureFormat::Astc4x4UnormSrgb,
    TextureFormat::Astc4x4Hdr,
    TextureFormat::Astc5x4Unorm,
    TextureFormat::Astc5x4UnormSrgb,
    TextureFormat::Astc5x4Hdr,
    TextureFormat::Astc5x5Unorm,
    TextureFormat::Astc5x5UnormSrgb,
    TextureFormat::Astc5x5Hdr,
    TextureFormat::Astc6x5Unorm,
    TextureFormat::Astc6x5UnormSrgb,
    TextureFormat::Astc6x5Hdr,
    TextureFormat::Astc6x6Unorm,
    TextureFormat::Astc6x6UnormSrgb,
    TextureFormat::Astc6x6Hdr,
    TextureFormat::Astc8x5Unorm,
    TextureFormat::Astc8x5UnormSrgb,
    TextureFormat::Astc8x5Hdr,
    TextureFormat::Astc8x6Unorm,
    TextureFormat::Astc8x6UnormSrgb,
    TextureFormat::Astc8x6Hdr,
    TextureFormat::Astc8x8Unorm,
    TextureFormat::Astc8x8UnormSrgb,
    TextureFormat::Astc8x8Hdr,
    TextureFormat::Astc10x5Unorm,
    TextureFormat::Astc10x5UnormSrgb,
    TextureFormat::Astc10x5Hdr,
    TextureFormat::Astc10x6Unorm,
    TextureFormat::Astc10x6UnormSrgb,
    TextureFormat::Astc10x6Hdr,
    TextureFormat::Astc10x8Unorm,
    TextureFormat::Astc10x8UnormSrgb,
    TextureFormat::Astc10x8Hdr,
    TextureFormat::Astc10x10Unorm,
    TextureFormat::Astc10x10UnormSrgb,
    TextureFormat::Astc10x10Hdr,
    TextureFormat::Astc12x10Unorm,
    TextureFormat::Astc12x10UnormSrgb,
    TextureFormat::Astc12x10Hdr,
    TextureFormat::Astc12x12Unorm,
    TextureFormat::Astc12x12UnormSrgb,
    TextureFormat::Astc12x12Hdr,
    TextureFormat::Bgra8Unorm,
    TextureFormat::Bgra8UnormSrgb,
    TextureFormat::R16Uint,
    TextureFormat::R16Sint,
    TextureFormat::R16Float,
    TextureFormat::R16Unorm,
    TextureFormat::R16Snorm,
    TextureFormat::Rg16Uint,
    TextureFormat::Rg16Sint,
    TextureFormat::Rg16Float,
    TextureFormat::Rg16Unorm,
    TextureFormat::Rg16Snorm,
    TextureFormat::Rgba16Uint,
    TextureFormat::Rgba16Sint,
    TextureFormat::Rgba16Float,
    TextureFormat::Rgba16Unorm,
    TextureFormat::Rgba16Snorm,
    TextureFormat::Rgb9e5Ufloat,
    TextureFormat::Rgb10a2Uint,
    TextureFormat::Rgb10a2Unorm,
    TextureFormat::Rg11b10Ufloat,
    TextureFormat::R32Uint,
    TextureFormat::R32Sint,
    TextureFormat::R32Float,
    TextureFormat::R64Uint,
    TextureFormat::Rg32Uint,
    TextureFormat::Rg32Sint,
    TextureFormat::Rg32Float,
    TextureFormat::Rgba32Uint,
    TextureFormat::Rgba32Sint,
    TextureFormat::Rgba32Float,
    TextureFormat::Depth16Unorm,
    TextureFormat::Depth32Float,
    TextureFormat::Depth32FloatStencil8,
    TextureFormat::Stencil8,
];

/// `*_SFLOAT_BLOCK` formats are legal to name only with the matching Vulkan
/// feature enabled. Keeping the classification next to `vk_format` prevents a
/// facts table from accidentally publishing an HDR mapping just because the
/// enum gained a native spelling.
pub(super) const fn is_astc_hdr(value: TextureFormat) -> bool {
    matches!(
        value,
        TextureFormat::Astc4x4Hdr
            | TextureFormat::Astc5x4Hdr
            | TextureFormat::Astc5x5Hdr
            | TextureFormat::Astc6x5Hdr
            | TextureFormat::Astc6x6Hdr
            | TextureFormat::Astc8x5Hdr
            | TextureFormat::Astc8x6Hdr
            | TextureFormat::Astc8x8Hdr
            | TextureFormat::Astc10x5Hdr
            | TextureFormat::Astc10x6Hdr
            | TextureFormat::Astc10x8Hdr
            | TextureFormat::Astc10x10Hdr
            | TextureFormat::Astc12x10Hdr
            | TextureFormat::Astc12x12Hdr
    )
}

pub(super) fn vk_format(value: TextureFormat) -> Option<vk::Format> {
    Some(match value {
        TextureFormat::R8Unorm => vk::Format::R8_UNORM,
        TextureFormat::R8Snorm => vk::Format::R8_SNORM,
        TextureFormat::R8Uint => vk::Format::R8_UINT,
        TextureFormat::R8Sint => vk::Format::R8_SINT,
        TextureFormat::Rg8Unorm => vk::Format::R8G8_UNORM,
        TextureFormat::Rg8Snorm => vk::Format::R8G8_SNORM,
        TextureFormat::Rg8Uint => vk::Format::R8G8_UINT,
        TextureFormat::Rg8Sint => vk::Format::R8G8_SINT,
        TextureFormat::Rgba8Unorm => vk::Format::R8G8B8A8_UNORM,
        TextureFormat::Rgba8UnormSrgb => vk::Format::R8G8B8A8_SRGB,
        TextureFormat::Rgba8Snorm => vk::Format::R8G8B8A8_SNORM,
        TextureFormat::Rgba8Uint => vk::Format::R8G8B8A8_UINT,
        TextureFormat::Rgba8Sint => vk::Format::R8G8B8A8_SINT,
        TextureFormat::Bc1RgbaUnorm => vk::Format::BC1_RGBA_UNORM_BLOCK,
        TextureFormat::Bc1RgbaUnormSrgb => vk::Format::BC1_RGBA_SRGB_BLOCK,
        TextureFormat::Bc2RgbaUnorm => vk::Format::BC2_UNORM_BLOCK,
        TextureFormat::Bc2RgbaUnormSrgb => vk::Format::BC2_SRGB_BLOCK,
        TextureFormat::Bc3RgbaUnorm => vk::Format::BC3_UNORM_BLOCK,
        TextureFormat::Bc3RgbaUnormSrgb => vk::Format::BC3_SRGB_BLOCK,
        TextureFormat::Bc4RUnorm => vk::Format::BC4_UNORM_BLOCK,
        TextureFormat::Bc4RSnorm => vk::Format::BC4_SNORM_BLOCK,
        TextureFormat::Bc5RgUnorm => vk::Format::BC5_UNORM_BLOCK,
        TextureFormat::Bc5RgSnorm => vk::Format::BC5_SNORM_BLOCK,
        TextureFormat::Bc6hRgbUfloat => vk::Format::BC6H_UFLOAT_BLOCK,
        TextureFormat::Bc6hRgbFloat => vk::Format::BC6H_SFLOAT_BLOCK,
        TextureFormat::Bc7RgbaUnorm => vk::Format::BC7_UNORM_BLOCK,
        TextureFormat::Bc7RgbaUnormSrgb => vk::Format::BC7_SRGB_BLOCK,
        TextureFormat::Etc2Rgb8Unorm => vk::Format::ETC2_R8G8B8_UNORM_BLOCK,
        TextureFormat::Etc2Rgb8UnormSrgb => vk::Format::ETC2_R8G8B8_SRGB_BLOCK,
        TextureFormat::Etc2Rgb8A1Unorm => vk::Format::ETC2_R8G8B8A1_UNORM_BLOCK,
        TextureFormat::Etc2Rgb8A1UnormSrgb => vk::Format::ETC2_R8G8B8A1_SRGB_BLOCK,
        TextureFormat::Etc2Rgba8Unorm => vk::Format::ETC2_R8G8B8A8_UNORM_BLOCK,
        TextureFormat::Etc2Rgba8UnormSrgb => vk::Format::ETC2_R8G8B8A8_SRGB_BLOCK,
        TextureFormat::EacR11Unorm => vk::Format::EAC_R11_UNORM_BLOCK,
        TextureFormat::EacR11Snorm => vk::Format::EAC_R11_SNORM_BLOCK,
        TextureFormat::EacRg11Unorm => vk::Format::EAC_R11G11_UNORM_BLOCK,
        TextureFormat::EacRg11Snorm => vk::Format::EAC_R11G11_SNORM_BLOCK,
        TextureFormat::Astc4x4Unorm => vk::Format::ASTC_4X4_UNORM_BLOCK,
        TextureFormat::Astc4x4UnormSrgb => vk::Format::ASTC_4X4_SRGB_BLOCK,
        TextureFormat::Astc4x4Hdr => vk::Format::ASTC_4X4_SFLOAT_BLOCK,
        TextureFormat::Astc5x4Unorm => vk::Format::ASTC_5X4_UNORM_BLOCK,
        TextureFormat::Astc5x4UnormSrgb => vk::Format::ASTC_5X4_SRGB_BLOCK,
        TextureFormat::Astc5x4Hdr => vk::Format::ASTC_5X4_SFLOAT_BLOCK,
        TextureFormat::Astc5x5Unorm => vk::Format::ASTC_5X5_UNORM_BLOCK,
        TextureFormat::Astc5x5UnormSrgb => vk::Format::ASTC_5X5_SRGB_BLOCK,
        TextureFormat::Astc5x5Hdr => vk::Format::ASTC_5X5_SFLOAT_BLOCK,
        TextureFormat::Astc6x5Unorm => vk::Format::ASTC_6X5_UNORM_BLOCK,
        TextureFormat::Astc6x5UnormSrgb => vk::Format::ASTC_6X5_SRGB_BLOCK,
        TextureFormat::Astc6x5Hdr => vk::Format::ASTC_6X5_SFLOAT_BLOCK,
        TextureFormat::Astc6x6Unorm => vk::Format::ASTC_6X6_UNORM_BLOCK,
        TextureFormat::Astc6x6UnormSrgb => vk::Format::ASTC_6X6_SRGB_BLOCK,
        TextureFormat::Astc6x6Hdr => vk::Format::ASTC_6X6_SFLOAT_BLOCK,
        TextureFormat::Astc8x5Unorm => vk::Format::ASTC_8X5_UNORM_BLOCK,
        TextureFormat::Astc8x5UnormSrgb => vk::Format::ASTC_8X5_SRGB_BLOCK,
        TextureFormat::Astc8x5Hdr => vk::Format::ASTC_8X5_SFLOAT_BLOCK,
        TextureFormat::Astc8x6Unorm => vk::Format::ASTC_8X6_UNORM_BLOCK,
        TextureFormat::Astc8x6UnormSrgb => vk::Format::ASTC_8X6_SRGB_BLOCK,
        TextureFormat::Astc8x6Hdr => vk::Format::ASTC_8X6_SFLOAT_BLOCK,
        TextureFormat::Astc8x8Unorm => vk::Format::ASTC_8X8_UNORM_BLOCK,
        TextureFormat::Astc8x8UnormSrgb => vk::Format::ASTC_8X8_SRGB_BLOCK,
        TextureFormat::Astc8x8Hdr => vk::Format::ASTC_8X8_SFLOAT_BLOCK,
        TextureFormat::Astc10x5Unorm => vk::Format::ASTC_10X5_UNORM_BLOCK,
        TextureFormat::Astc10x5UnormSrgb => vk::Format::ASTC_10X5_SRGB_BLOCK,
        TextureFormat::Astc10x5Hdr => vk::Format::ASTC_10X5_SFLOAT_BLOCK,
        TextureFormat::Astc10x6Unorm => vk::Format::ASTC_10X6_UNORM_BLOCK,
        TextureFormat::Astc10x6UnormSrgb => vk::Format::ASTC_10X6_SRGB_BLOCK,
        TextureFormat::Astc10x6Hdr => vk::Format::ASTC_10X6_SFLOAT_BLOCK,
        TextureFormat::Astc10x8Unorm => vk::Format::ASTC_10X8_UNORM_BLOCK,
        TextureFormat::Astc10x8UnormSrgb => vk::Format::ASTC_10X8_SRGB_BLOCK,
        TextureFormat::Astc10x8Hdr => vk::Format::ASTC_10X8_SFLOAT_BLOCK,
        TextureFormat::Astc10x10Unorm => vk::Format::ASTC_10X10_UNORM_BLOCK,
        TextureFormat::Astc10x10UnormSrgb => vk::Format::ASTC_10X10_SRGB_BLOCK,
        TextureFormat::Astc10x10Hdr => vk::Format::ASTC_10X10_SFLOAT_BLOCK,
        TextureFormat::Astc12x10Unorm => vk::Format::ASTC_12X10_UNORM_BLOCK,
        TextureFormat::Astc12x10UnormSrgb => vk::Format::ASTC_12X10_SRGB_BLOCK,
        TextureFormat::Astc12x10Hdr => vk::Format::ASTC_12X10_SFLOAT_BLOCK,
        TextureFormat::Astc12x12Unorm => vk::Format::ASTC_12X12_UNORM_BLOCK,
        TextureFormat::Astc12x12UnormSrgb => vk::Format::ASTC_12X12_SRGB_BLOCK,
        TextureFormat::Astc12x12Hdr => vk::Format::ASTC_12X12_SFLOAT_BLOCK,
        TextureFormat::Bgra8Unorm => vk::Format::B8G8R8A8_UNORM,
        TextureFormat::Bgra8UnormSrgb => vk::Format::B8G8R8A8_SRGB,
        TextureFormat::R16Uint => vk::Format::R16_UINT,
        TextureFormat::R16Sint => vk::Format::R16_SINT,
        TextureFormat::R16Float => vk::Format::R16_SFLOAT,
        TextureFormat::R16Unorm => vk::Format::R16_UNORM,
        TextureFormat::R16Snorm => vk::Format::R16_SNORM,
        TextureFormat::Rg16Uint => vk::Format::R16G16_UINT,
        TextureFormat::Rg16Sint => vk::Format::R16G16_SINT,
        TextureFormat::Rg16Float => vk::Format::R16G16_SFLOAT,
        TextureFormat::Rg16Unorm => vk::Format::R16G16_UNORM,
        TextureFormat::Rg16Snorm => vk::Format::R16G16_SNORM,
        TextureFormat::Rgba16Uint => vk::Format::R16G16B16A16_UINT,
        TextureFormat::Rgba16Sint => vk::Format::R16G16B16A16_SINT,
        TextureFormat::Rgba16Float => vk::Format::R16G16B16A16_SFLOAT,
        TextureFormat::Rgba16Unorm => vk::Format::R16G16B16A16_UNORM,
        TextureFormat::Rgba16Snorm => vk::Format::R16G16B16A16_SNORM,
        TextureFormat::Rgb9e5Ufloat => vk::Format::E5B9G9R9_UFLOAT_PACK32,
        TextureFormat::Rgb10a2Uint => vk::Format::A2B10G10R10_UINT_PACK32,
        TextureFormat::Rgb10a2Unorm => vk::Format::A2B10G10R10_UNORM_PACK32,
        TextureFormat::Rg11b10Ufloat => vk::Format::B10G11R11_UFLOAT_PACK32,
        TextureFormat::R32Uint => vk::Format::R32_UINT,
        TextureFormat::R32Sint => vk::Format::R32_SINT,
        TextureFormat::R32Float => vk::Format::R32_SFLOAT,
        TextureFormat::R64Uint => vk::Format::R64_UINT,
        TextureFormat::Rg32Uint => vk::Format::R32G32_UINT,
        TextureFormat::Rg32Sint => vk::Format::R32G32_SINT,
        TextureFormat::Rg32Float => vk::Format::R32G32_SFLOAT,
        TextureFormat::Rgba32Uint => vk::Format::R32G32B32A32_UINT,
        TextureFormat::Rgba32Sint => vk::Format::R32G32B32A32_SINT,
        TextureFormat::Rgba32Float => vk::Format::R32G32B32A32_SFLOAT,
        TextureFormat::Depth16Unorm => vk::Format::D16_UNORM,
        TextureFormat::Depth32Float => vk::Format::D32_SFLOAT,
        TextureFormat::Depth32FloatStencil8 => vk::Format::D32_SFLOAT_S8_UINT,
        TextureFormat::Stencil8 => vk::Format::S8_UINT,
        // These portable aliases deliberately do not name a fixed Vulkan
        // layout.  Multi-planar images require a separate plane-aware image
        // creation/view/copy slice; keep them unavailable until that lowering
        // exists rather than publishing a VkFormat that the rest of this
        // backend cannot use correctly.
        TextureFormat::Depth24Plus
        | TextureFormat::Depth24PlusStencil8
        | TextureFormat::Nv12
        | TextureFormat::P010 => return None,
    })
}
